//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_NorthwindUygulama.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Araclar
    {
        public int AracId { get; set; }
        public string AracMarkasi { get; set; }
        public string AracPlakasi { get; set; }
        public System.DateTime AracYapimYili { get; set; }
    }
}
