//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_NorthwindUygulama.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quality
    {
        public int id { get; set; }
        public int star { get; set; }
        public int OrderDetailID1 { get; set; }
        public int OrderDetailID2 { get; set; }
    }
}
