//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_NorthwindUygulama.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sa_KISILER
    {
        public int ID { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public Nullable<short> Yas { get; set; }
        public string Telefon { get; set; }
        public Nullable<System.DateTime> Dogum_Tarihi { get; set; }
        public string Dili { get; set; }
    }
}
