//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_NorthwindUygulama.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_musteriPersonelSiparisleri
    {
        public int OrderID { get; set; }
        public string Ad_Soyad { get; set; }
        public Nullable<int> Yaş { get; set; }
        public string CompanyName { get; set; }
        public string Phone { get; set; }
        public string Order_date { get; set; }
        public Nullable<decimal> freight { get; set; }
    }
}
